repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
      additional_dependencies: [-e, 'git+https://github.com/pycqa/pyflakes@2.2.0#egg=pyflakes', -e, 'git+https://github.com/pycqa/pycodestyle@2.6.0#egg=pycodestyle']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
